#ifndef __SYSLOG_CONFIG_H__
#define __SYSLOG_CONFIG_H__

//#define _SYSLOG_USE_NETWORK
#define _SYSLOG_USE_FILE
//#define _SYSLOG_USE_SD_FAT
#define _SYSLOG_USE_HARDWARE_SERIAL
//#define _SYSLOG_USE_SOFTWARE_SERIAL

#define _SYSLOG_OUTPUT_TIME
#define _SYSLOG_USE_RTC
//#define _SYSLOG_USE_NTP

#endif /* __SYSLOG_CONFIG_H__ */
